- name: Install device-mapper-persistent-data  # This task installs the device-mapper-persistent-data package.
  yum:
    name: device-mapper-persistent-data
    state: latest  # The latest version of the package will be installed.

- name: Install lvm2  # This task installs the lvm2 package.
  yum:
    name: lvm2
    state: latest  # The latest version of the package will be installed.

- name: add repo docker  # This task adds the Docker repository to the system's repository list.
  command:
    cmd: sudo yum-config-manager --add-repo=https://download.docker.com/linux/centos/docker-ce.repo

- name: Install Docker  # This task installs Docker.
  yum:
    name: docker-ce
    state: present  # The Docker package will be installed if it's not already present.

- name: Install python3  # This task installs Python 3.
  yum:
    name: python3
    state: present  # The Python 3 package will be installed if it's not already present.

- name: Install docker with Python 3  # This task installs the Docker Python library using pip3.
  pip:
    name: docker
    executable: pip3
  vars:
    ansible_python_interpreter: /usr/bin/python3  # This sets the Python interpreter to be used by Ansible to Python 3.

- name: Make sure Docker is running  # This task ensures that the Docker service is running.
  service: name=docker state=started
  tags: docker  # This task is tagged with 'docker', which can be used to run this specific task with the '--tags' option.

  